### ISSUE TITLE
Hacktober Issue 

### ISSUE THREAD

**Issue by miniam** [miniam/Algorithms-and-dataStructures#3]
### contribute as much as you can

**Comment by abhishekds94** [comment]
Working on this.

**Comment by Pacheco95** [comment]
I think the source codes must be more structured like the following:

- Programming Language
  - Algorithms
    - Specific algorithms & datastructures
  - GeneralAlgorithms
    - Tree (interface)
      - Implementation 1
      - Implementation 2
      - Implementation 3
    - Stack (interface)
      - Implementation 1
      - Implementation 2
      - Implementation 3
    - Queue (interface)
      - Implementation 1
      - Implementation 2
      - Implementation 3

**Comment by rusyasoft** [comment]
Here is my PR https://github.com/miniam/Algorithms-and-dataStructures/pull/9

**Comment by nazneennahar** [comment]
how exactly do you want us to contribute? do you want us to modify the code and make it simpler etc?
